name: CI

on:
  push:
    tags:
      - "ver*.*"
  workflow_dispatch:  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true
          clean: true
          fetch-depth: 1
          submodules: true
      - name: ffmpeg
        run: |1
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          ffmpeg -version
      - name: set-output tag value
        id: tag
        run: echo ::set-output name=value::${GITHUB_REF/refs\/tags\//}
      - name: Create zip
        run: |
          ffmpeg -i GeneralAtsPlugin/Unicorn/sound/ats_p_bell.wav -af "volume=-5dB" E233-3000/ExternalData/Sound/ats_p_bell.wav
          mkdir deploy
          zip deploy/${{ steps.tag.outputs.value }}.zip -r E233-3000
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            deploy/${{ steps.tag.outputs.value }}.zip
